language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-kurea' ]; then cd .. && eval "mv $currentfolder generator-kurea" && cd generator-kurea; fi
